# Generated by Django 2.1.7 on 2019-03-02 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190303_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='auth_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=250)),
                ('employee_password', models.CharField(max_length=250)),
                ('employee_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
            ],
        ),
    ]
