# Generated by Django 2.1.7 on 2019-03-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auth_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dp',
            field=models.CharField(default='WhatsApp Image 2018-11-11 at 5.54.10 PM.jpeg', max_length=1000),
        ),
    ]
