# Generated by Django 2.1.7 on 2019-03-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_employee_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth_data',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
