# Generated by Django 2.1.7 on 2019-03-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auth_data_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dp',
            field=models.FileField(upload_to=''),
        ),
    ]
