# Generated by Django 2.1.7 on 2019-04-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190329_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='video',
            field=models.FileField(default='stack.mp4', upload_to=''),
        ),
    ]
