# Generated by Django 2.1.7 on 2019-04-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_employee_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='video',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
