# Generated by Django 2.1.7 on 2019-04-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190403_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='video',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
    ]
